package he4rt.open.tibia.world.game.map.tile;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum TileEnum {

    TILESTATE_NONE(0),
    TILESTATE_FLOORCHANGE_DOWN(1),
    TILESTATE_FLOORCHANGE_NORTH(2),
    TILESTATE_FLOORCHANGE_SOUTH(4),
    TILESTATE_FLOORCHANGE_EAST(8),
    TILESTATE_FLOORCHANGE_WEST(16),
    TILESTATE_FLOORCHANGE_SOUTH_ALT(32),
    TILESTATE_FLOORCHANGE_EAST_ALT(64),
    TILESTATE_PROTECTIONZONE(128),
    TILESTATE_NOPVPZONE(256),
    TILESTATE_NOLOGOUT(512),
    TILESTATE_PVPZONE(1024),
    TILESTATE_TELEPORT(2048),
    TILESTATE_MAGICFIELD(4096),
    TILESTATE_MAILBOX(8192),
    TILESTATE_TRASHHOLDER(16384),
    TILESTATE_BED(32768),
    TILESTATE_DEPOT(65536),
    TILESTATE_BLOCKSOLID(131072),
    TILESTATE_BLOCKPATH(262144),
    TILESTATE_IMMOVABLEBLOCKSOLID(524288),
    TILESTATE_IMMOVABLEBLOCKPATH(1048576),
    TILESTATE_IMMOVABLENOFIELDBLOCKPATH(2097152),
    TILESTATE_NOFIELDBLOCKPATH(4194304),
    TILESTATE_SUPPORTS_HANGABLE(8388608);

    private final int value;

    public boolean hasFlag(long flags) {
        return (flags & getValue()) == getValue();
    }
}
