package he4rt.open.tibia.base.core.io.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;

@AllArgsConstructor
@Getter
public enum RecvOpcodeEnum implements IEnums {

    RECV_UNKNOW(-1),
    RECV_DEFAULT(0),
    RECV_PLAYERLOGINREQUEST(1),
    RECV_PLAYERLOGIN(10),
    RECV_PLAYERLOGOUT(20),
    RECV_PING(30),
    RECV_AUTOMOVE(100),
    RECV_WALKNORTH(101),
    RECV_WALKEAST(102),
    RECV_WALKSOUTH(103),
    RECV_WALKWEST(104),
    RECV_CANCELAUTOWALK(105),
    RECV_WALKNORTEAST(106),
    RECV_WALKSOUTHEAST(107),
    RECV_WALKSOUTHWEST(108),
    RECV_WALKNORTHWEST(109),
    RECV_TURNNORTH(111),
    RECV_TURNEAST(112),
    RECV_TURNSOUTH(113),
    RECV_TURNWEST(114),
    RECV_ITEMTHROW(120),
    RECV_PLAYERPURCHASE(122),
    RECV_PLAYERSALE(123),
    RECV_CLOSESHOP(124),
    RECV_TRADEREQUEST(125),
    RECV_TRADELOOK(126),
    RECV_TRADEACCEPT(127),
    RECV_TRADECANCEL(128),
    RECV_ITEMUSE(130),
    RECV_ITEMUSEON(131),
    RECV_ITEMUSEONCREATURE(132),
    RECV_ITEMROTATE(133),
    RECV_CONTAINERCLOSE(135),
    RECV_CONTAINERUP(136),
    RECV_WINDOWTEXT(137),
    RECV_WINDOWHOUSE(138),
    RECV_LOOKAT(140),
    RECV_LOOKINBATTLELIST(141),
    RECV_JOINAGRESSION(142),
    RECV_SPEECH(150),
    RECV_CHANNELLISTREQUEST(151),
    RECV_CHANNELOPEN(152),
    RECV_CHANNELCLOSE(153),
    RECV_CHANNELOPENPRIVATE(154),
    RECV_REPORTPROCESS(155),
    RECV_REPORTCLOSE(156),
    RECV_REPORTCANCEL(157),
    RECV_NPCCHANNELCLOSE(158),
    RECV_CHANGEMODES(160),
    RECV_ATTACK(161),
    RECV_FOLLOW(162),
    RECV_PARTYINVITE(163),
    RECV_PARTYJOIN(164),
    RECV_PARTYREVOKE(165),
    RECV_PARTYPASSLEADERSHIP(166),
    RECV_PARTYLEAVE(167),
    RECV_ENABLESHAREDEXP(168),
    RECV_CHANNELCREATEPRIVATE(170),
    RECV_CHANNELINVITE(171),
    RECV_CHANNELEXCLUDE(172),
    RECV_STOPALLACTIONS(190),
    RECV_RESENDTILE(201),
    RECV_RESENTCONTAINER(202),
    RECV_OUTFITCHANGEREQUEST(210),
    RECV_OUTFITCHANGECOMPLETED(211),
    RECV_ADDVIP(220),
    RECV_REMOVEVIP(221),
    RECV_REPORTBUG(230),
    RECV_REPORTVIOLATION(231),
    RECV_REPORTDEBUGASSERTION(232),
    RECV_ANY(255)
    ;

    private int value;

    public static RecvOpcodeEnum getByIntegerValue(int opCode) {
        return Arrays.stream(RecvOpcodeEnum.values()).filter(e -> e.getValue() == opCode).findFirst().orElse(RECV_UNKNOW);

    }
}
